### ISSUE TITLE
always appear those troubles

### ISSUE THREAD

**Issue by ChrisLou-bioinfo** [LosicLab/starchip#11]
[root@VM_32_17_centos starchip]# ./Step1.sh 
Filtering out chimeric reads that appear circular
Filtering circular reads based on assigned thresholds of 5 reads in 1 individuals
Argument "8680r7" isn't numeric in subtraction (-) at /root/starchip/scripts/circles/merge_close_crna_1file.pl line 26, <> line 1588.
creating circRNA fasta and gtf for re-alignment and quantification
Use of uninitialized value $pos2 in subtraction (-) at /root/starchip/scripts/circles/id2fasta_gtf.pl line 32, <CIRCLES> line 298.
Use of uninitialized value $pos2 in subtraction (-) at /root/starchip/scripts/circles/id2fasta_gtf.pl line 37, <CIRCLES> line 298.
Use of uninitialized value $pos2 in concatenation (.) or string at /root/starchip/scripts/circles/id2fasta_gtf.pl line 39, <CIRCLES> line 298.
Argument "8680r7" isn't numeric in subtraction (-) at /root/starchip/scripts/circles/id2fasta_gtf.pl line 32, <CIRCLES> line 1455.
Argument "chr7" isn't numeric in subtraction (-) at /root/starchip/scripts/c

**Comment by ChrisLou-bioinfo** [comment]
12hours ago, it works ，why？

**Comment by kippakers** [comment]
Hi ChrisLou,

I'm trying to sort out what's going wrong for you.  Does your most recent comment indicate that STARChip is now running without errors for you?  Are your multiple messages about 1 sample, 1 cohort, or many samples, or many cohorts?  

In the case above you appear to have just one circRNA that is listed with nonsensical position, "8680r7".  Can you search for this string in your file rawdata/cRNA.cutoff.5 and tell me what you find?  

Thanks,
Kipp
