### ISSUE TITLE
another trouble

### ISSUE THREAD

**Issue by ChrisLou-bioinfo** [LosicLab/starchip#14]
Error: requested chromosome 0 does not exist in the genome file /root/files/circular_ref/gencode.v28.primary_assembly.annotation.gtf.exons.genome. Exiting.
Use of uninitialized value $p2Info in split at /root/files/starchip/scripts/circles/summarize_geneinfo.pl line 12, <> line 1.
Use of uninitialized value in string eq at /root/files/starchip/scripts/circles/summarize_geneinfo.pl line 20, <> line 1.
Use of uninitialized value in string eq at /root/files/starchip/scripts/circles/summarize_geneinfo.pl line 20, <> line 1.
Use of uninitialized value $p1Distance in string eq at /root/files/starchip/scripts/circles/summarize_geneinfo.pl line 24, <> line 1.
Use of uninitialized value $p1Distance in string eq at /root/files/starchip/scripts/circles/summarize_geneinfo.pl line 24, <> line 1.
Use of uninitialized value $p1Distance in numeric eq (==) at /root/files/starchip/scripts/circles/summarize_geneinfo.pl line 27, <> line 1.
Use of uninitialized value $p2Distance in numeric eq (==) at /root/files/starchip/scripts/circles/summarize_geneinfo.pl line 27, <> line 1.

**Comment by kippakers** [comment]
All of your issues should be solved in v1.3c, thanks!
