### ISSUE TITLE
Unable to go on with Step2.sh

### ISSUE THREAD

**Issue by Sealzad** [LosicLab/starchip#15]
Hi,

I have used STARchip to carry out the circular RNA identification from fasta. so I have four 'step' scripts. 

I could complete the first one - Step1.sh - with no issues but Step2 keeps giving me this msg:

"No such file or directory at /root/programfiles/starchip/scripts/circles/chimera-score.pl line 23"

Firstly, I don't know it is getting this problem. I thought it was in Step2.sh but line 23 does not have this inquiry. Then I thought it was the chimera-score.pl. But it, too, did not have any such inquiry at line 23. So it is confusing. 

I think the program has much potential but the installation and execution is confusing; I couldn't get it to work without the need to go through STAR internally. 

Actually, is there any reason why the program cannot create one final script, and then execute it entirely from there? Is there a need to set up "check points" with the 4 scripts?

Thank you.

**Comment by kippakers** [comment]
Thanks for pointing this out and all the details via email.  This should be fixed in v1.3d.
