### ISSUE TITLE
I don't know where the reference gtf should be placed，always point out “ can not open file”

### ISSUE THREAD

**Issue by biozhao** [LosicLab/starchip#16]
I ran starchip-fusions.pl 
question description form output file,such as:
read length error, please check input.  Using 100bp as a guess.
Error: Can't open genome file/path/to/gencode.v26.primary_assembly.annotation.gtf.exons.genomeExiting...
Error: Unable to open file /path/to/hg38.repeats.bed. Exiting.
No fusions discovered.  Consider lowering read requirements to increase sensitivity.

**Comment by kippakers** [comment]
Hi Biozhao,

You need to go through more setup before running STARChip.  In your parameters file, you are telling starchip to look for:

/path/to/gencode.v26.primary_assembly.annotation.gtf.exons

Replace that, and all other paths, with accurate paths specific to your system.  You can put your reference gtf wherever you'd like, just tell STARChip where it is.  

Good luck!

**Comment by biozhao** [comment]
thanks a lot
