### ISSUE TITLE
trouble when using Step1.sh

### ISSUE THREAD

**Issue by biozhao** [LosicLab/starchip#17]
Hi
  When i used to Step1.sh, i got a point "_awk: 1: unexpected character '.'
                                                                cut: rawdata/cRNA.cutoff.5: No such file or directory_"

 than i changed code in Step1.sh, form " awk -v var= -v var2=rawdata/cRNA.cutoff." to " awk -v var= -v var2=rawdata/cRNA.cutoff.${cutoff} "
however , i got the same error.

Thank you for your attention

**Comment by kippakers** [comment]
Hello,

Please send me the command you used to run STARChip, your parameters file, and the list of fastqs or STAR alignments that you gave STARChip.  You can send them to me at nicholas.kipp.akers@gmail.com

Thanks!
Kipp

**Comment by biozhao** [comment]
thanks a lot
