### ISSUE TITLE
STARChip circles error when testing example data

### ISSUE THREAD

**Issue by giuseppedelnapalle** [LosicLab/starchip#19]
An error bothered me when I was doing STARChip circle detection on example data. I run Step1.sh fully according to the instruction but I got the error message: 

> Filtering out chimeric reads that appear circular
> Filtering circular reads based on assigned thresholds of 5 reads in 1 individuals
> awk: cmd. line:1: { if (5 >= var) print /home/xxyy/Public/Bio_data/RNA_seq/XXXX/circRNA/starchip-master/example/STARChip-circRNA/scripts/circles/circle_star.sh >> var2 }
> awk: cmd. line:1:                                                                                                                                                               ^ syntax error
> awk: cmd. line:1: { if (5 >= var) print /home/xxyy/Public/Bio_data/RNA_seq/XXXX/circRNA/starchip-master/example/STARChip-circRNA/scripts/circles/circle_star.sh >> var2 }
> awk: cmd. line:1:                                                                                                                                                               ^ syntax error
> cut: rawdata/cRNA.cutoff.5: No such file or directory
> creating circRNA fasta and gtf for re-alignment and quantification

Previously, I followed the instructions to download the annotation file (.gtf) and genome file (.fa), run setup.sh and then starchip-circles.pl, which finally generated Step1.sh and Step2.sh. All these steps went smoothly.

Actually, I also run starchip-circles.pl starting from .fastq files with my own data and got the same error message.

I truly appreciate any help. Thanks in advance!

**Comment by kippakers** [comment]
Thanks so much for the report! I found the bug causing this issue, it should be fixed in v1.3e.
