### ISSUE TITLE
merge close circRNA

### ISSUE THREAD

**Issue by huangziyan11111** [LosicLab/starchip#21]
Hi, I have a question about the circRNAs with close position. in the paper you said: CircRNA reads passing these filters are then merged if junction ends are very close.
while in the code,is this script starchip/scripts/circles/filter_circsv3.pl can fulfill this merge step? and which parameter can handle it?

**Comment by kippakers** [comment]
Hi, sorry this took so long to respond, I missed the notification!  

This process is handled by merge_close_crna_1file.pl , it merges circRNA with the same chromosome, and the splice donor and splice acceptor are within 10bp.  At the top of that script is a set parameter called $distancemax, you can change 10 to whatever value you want.  

Cheers,
Kipp
