### ISSUE TITLE
run starchip-circles.pl problem

### ISSUE THREAD

**Issue by lzhmercury** [LosicLab/starchip#25]
Dear 
1. Is the 'sample1/2' in the 'stardirs.txt' path to STAR aligned out fold or the exact Chimeric.out.junction file? 2. Besides, do we have to fill the 'starprefix' in the starchip-circles.params file, so that the starchip-circles.pl can exact recognize the STAR aligned out files?
3. I notice a bug, I run starchip-circles.pl without any file produced in rawdata fold, but can generate Step1.sh as well as Step2.sh. I work as instructed: ensemble GTF and fasta downloaded; refbed generated by step.sh; STAR aligned; starchip-circles.params used default value, but nothing came out.
Could you please tell me how to deal with these problem? Many thanks

**Comment by kippakers** [comment]
Hi Izhmercury,

1. Just path to the directory, not the junction file.  It looks at several STAR outputs.  Unless you used an output prefix in your STAR run, you don't need anything for the starprefix parameter.
2.  After you generate Step1.sh and Step2.sh, you need to run those scripts (e.g put "./Step1.sh " into your terminal ) .  Sorry if I misunderstand. 

I hope that helps!
Kipp
