### ISSUE TITLE
comment on ms

### ISSUE THREAD

**Issue by mikelove** [LosicLab/starchip#7]
a minor comment, it looks like you use limma-voom in the software and Fig 3, maybe worth a cite?

**Comment by kippakers** [comment]
Good catch.  The limma reference got pushed to the supplemental methods, but as it's used in the main text figure I should have gotten it in the main text.  

It is listed on the software dependencies list [here](http://starchimp.readthedocs.io/en/latest/#installation) and [here](https://github.com/LosicLab/starchip).  But your comment made me realize I was omitting gplots from those lists.

Thanks!

**Comment by mikelove** [comment]
np. looks interesting! cheers
