### ISSUE TITLE
Bedtools 2.26.0 Compatibility Issues

### ISSUE THREAD

**Issue by dmaloneynygc** [LosicLab/starchip#8]
Doesn't seem the call to closest in cRNA_coordinates2genes.sh line 10 is 2.26.0 compatible.

Receive this --  Error: Type checker found wrong number of fields while tokenizing data line.

Works for version 2.25.0.

**Comment by kippakers** [comment]
Thanks for the report!  I've patched the issue, it should work with bedtools 2.26+ now.
